#pragma once
// Generated by lv2/tools/gen_bundle.py from lv2/tools/ports.py - do not edit.
//
// The same table generates AmbienceReverb.ttl, so a port cannot exist in the
// TTL without existing here (and vice versa) and the indices cannot disagree.

#define AMBIENCE_URI "https://github.com/OTODESK4193/Ambience1.0.1"

namespace ambience {

enum PortIndex {
    PORT_IN_L           = 0,
    PORT_IN_R           = 1,
    PORT_OUT_L          = 2,
    PORT_OUT_R          = 3,

    PORT_ALGORITHM      = 4,
    PORT_PREDELAY       = 5,
    PORT_ROOMSIZE       = 6,
    PORT_DECAYTIME      = 7,
    PORT_HFDAMPING      = 8,
    PORT_LFABSORPTION   = 9,
    PORT_DIFFUSION      = 10,
    PORT_MODAMOUNT      = 11,
    PORT_MODRATE        = 12,
    PORT_STEREOWIDTH    = 13,
    PORT_ERLEVEL        = 14,
    PORT_SATURATION     = 15,
    PORT_SATTYPE        = 16,
    PORT_WETLEVEL       = 17,
    PORT_DRYLEVEL       = 18,
    PORT_DUCKAMOUNT     = 19,
    PORT_DUCKATTACK     = 20,
    PORT_DUCKRELEASE    = 21,
    PORT_DUCKTHRESH     = 22,
    PORT_ERSOLO         = 23,
    PORT_PROMODE        = 24,
    PORT_TILTLOW        = 25,
    PORT_TILTMID        = 26,
    PORT_TILTHIGH       = 27,
    PORT_RTBAND0        = 28,
    PORT_RTBAND1        = 29,
    PORT_RTBAND2        = 30,
    PORT_RTBAND3        = 31,
    PORT_RTBAND4        = 32,
    PORT_RTBAND5        = 33,
    PORT_RTBAND6        = 34,
    PORT_RTBAND7        = 35,
    PORT_RTBAND8        = 36,
    PORT_RTBAND9        = 37,
    PORT_LOCUT          = 38,
    PORT_HICUT          = 39,

    PORT_COUNT              = 40
};

// Indices into the control[] array, i.e. port index minus kFirstControlPort.
enum ControlIndex {
    CTL_ALGORITHM       = 0,
    CTL_PREDELAY        = 1,
    CTL_ROOMSIZE        = 2,
    CTL_DECAYTIME       = 3,
    CTL_HFDAMPING       = 4,
    CTL_LFABSORPTION    = 5,
    CTL_DIFFUSION       = 6,
    CTL_MODAMOUNT       = 7,
    CTL_MODRATE         = 8,
    CTL_STEREOWIDTH     = 9,
    CTL_ERLEVEL         = 10,
    CTL_SATURATION      = 11,
    CTL_SATTYPE         = 12,
    CTL_WETLEVEL        = 13,
    CTL_DRYLEVEL        = 14,
    CTL_DUCKAMOUNT      = 15,
    CTL_DUCKATTACK      = 16,
    CTL_DUCKRELEASE     = 17,
    CTL_DUCKTHRESH      = 18,
    CTL_ERSOLO          = 19,
    CTL_PROMODE         = 20,
    CTL_TILTLOW         = 21,
    CTL_TILTMID         = 22,
    CTL_TILTHIGH        = 23,
    CTL_RTBAND0         = 24,
    CTL_RTBAND1         = 25,
    CTL_RTBAND2         = 26,
    CTL_RTBAND3         = 27,
    CTL_RTBAND4         = 28,
    CTL_RTBAND5         = 29,
    CTL_RTBAND6         = 30,
    CTL_RTBAND7         = 31,
    CTL_RTBAND8         = 32,
    CTL_RTBAND9         = 33,
    CTL_LOCUT           = 34,
    CTL_HICUT           = 35,
};

constexpr int kFirstControlPort = 4;
constexpr int kNumControlPorts  = 36;

struct ControlDesc { const char* sym; float lo, hi, def; };

constexpr ControlDesc kControls[kNumControlPorts] = {
    { "algorithm", 0.0f, 6.0f, 0.0f },
    { "predelay", 0.0f, 500.0f, 10.0f },
    { "roomsize", 0.3f, 2.0f, 1.0f },
    { "decaytime", 0.1f, 20.0f, 1.5f },
    { "hfdamping", 0.0f, 1.0f, 0.0f },
    { "lfabsorption", 0.0f, 1.0f, 0.0f },
    { "diffusion", 0.0f, 1.0f, 0.7f },
    { "modamount", 0.0f, 1.0f, 0.25f },
    { "modrate", 0.05f, 2.0f, 0.5f },
    { "stereowidth", 0.0f, 1.0f, 0.8f },
    { "erlevel", 0.0f, 1.0f, 0.6f },
    { "saturation", 0.0f, 1.0f, 0.0f },
    { "sattype", 0.0f, 3.0f, 0.0f },
    { "wetlevel", -60.0f, 0.0f, -4.0f },
    { "drylevel", -60.0f, 0.0f, 0.0f },
    { "duckamount", 0.0f, 20.0f, 0.0f },
    { "duckattack", 0.5f, 100.0f, 10.0f },
    { "duckrelease", 10.0f, 2000.0f, 200.0f },
    { "duckthresh", -60.0f, 0.0f, -20.0f },
    { "ersolo", 0.0f, 1.0f, 0.0f },
    { "promode", 0.0f, 1.0f, 0.0f },
    { "tiltlow", 0.5f, 2.0f, 1.0f },
    { "tiltmid", 0.5f, 2.0f, 1.0f },
    { "tilthigh", 0.5f, 2.0f, 1.0f },
    { "rtband0", 0.5f, 2.0f, 1.0f },
    { "rtband1", 0.5f, 2.0f, 1.0f },
    { "rtband2", 0.5f, 2.0f, 1.0f },
    { "rtband3", 0.5f, 2.0f, 1.0f },
    { "rtband4", 0.5f, 2.0f, 1.0f },
    { "rtband5", 0.5f, 2.0f, 1.0f },
    { "rtband6", 0.5f, 2.0f, 1.0f },
    { "rtband7", 0.5f, 2.0f, 1.0f },
    { "rtband8", 0.5f, 2.0f, 1.0f },
    { "rtband9", 0.5f, 2.0f, 1.0f },
    { "locut", 20.0f, 500.0f, 20.0f },
    { "hicut", 1000.0f, 20000.0f, 20000.0f },
};

} // namespace ambience
