#!/usr/bin/env python3
"""
Generate everything in the Ambience LV2 bundle that is derived from something
else, so none of it can drift:

    lv2/src/ports.h        port indices + defaults for the C++ wrapper
    AmbienceReverb.ttl     the port descriptions mod-ui and lilv read
    manifest.ttl           plugin + one inline stanza per preset
    presets.ttl            28 presets
    default-preset.ttl     the layout defaults, as MOD's own bundles ship
    modgui.ttl             modgui:port entries for all 40 ports

Sources of truth:
    lv2/tools/ports.py         the port table (transcribed from
                               Source/PluginParameters.cpp)
    Presets/*.ambpreset        21 factory presets
    Source/AlgorithmPresets.h  PRESET_DEFAULTS -> 7 "<ALGO> Default" presets

Run from the repo root:  python3 lv2/tools/gen_bundle.py
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ports as P

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

URI = "https://github.com/OTODESK4193/Ambience1.0.1"
PRESET_NS = URI + "/presets#"
VERSION = (1, 1)  # minorVersion, microVersion

BUNDLE = os.path.join(REPO, "lv2", "bundle")
PORTS_H = os.path.join(REPO, "lv2", "src", "ports.h")

PROLOGUE = "# Generated by lv2/tools/gen_bundle.py - do not edit by hand.\n"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def num(v):
    """TTL numeric literal. Integers must not be written as 1.0 where lilv
    expects an integer-typed port value, and floats must keep a decimal point
    or they parse as xsd:integer."""
    if isinstance(v, int):
        return str(v)
    if float(v).is_integer() and abs(v) < 1e15:
        return "%.1f" % v
    return repr(round(float(v), 6))


def ttl_string(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


UNIT_TTL = {"ms": "units:ms", "s": "units:s", "hz": "units:hz", "db": "units:db"}


# ---------------------------------------------------------------------------
# lv2/src/ports.h
# ---------------------------------------------------------------------------
def gen_ports_h():
    out = ["""#pragma once
// Generated by lv2/tools/gen_bundle.py from lv2/tools/ports.py - do not edit.
//
// The same table generates AmbienceReverb.ttl, so a port cannot exist in the
// TTL without existing here (and vice versa) and the indices cannot disagree.

#define AMBIENCE_URI "%s"

namespace ambience {

enum PortIndex {""" % URI]

    for i, (sym, _name, _dir) in enumerate(P.AUDIO_PORTS):
        out.append("    PORT_%-14s = %d," % (sym.upper(), i))
    out.append("")

    for i, p in enumerate(P.CONTROL_PORTS):
        out.append("    PORT_%-14s = %d," % (p["sym"].upper(),
                                             P.FIRST_CONTROL_INDEX + i))
    out.append("")
    out.append("    PORT_COUNT              = %d" %
               (len(P.AUDIO_PORTS) + len(P.CONTROL_PORTS)))
    out.append("};")
    out.append("")
    out.append("// Indices into the control[] array, i.e. port index minus"
               " kFirstControlPort.")
    out.append("enum ControlIndex {")
    for i, p in enumerate(P.CONTROL_PORTS):
        out.append("    CTL_%-15s = %d," % (p["sym"].upper(), i))
    out.append("};")
    out.append("")
    out.append("constexpr int kFirstControlPort = %d;" % P.FIRST_CONTROL_INDEX)
    out.append("constexpr int kNumControlPorts  = %d;" % len(P.CONTROL_PORTS))
    out.append("")
    out.append("struct ControlDesc { const char* sym; float lo, hi, def; };")
    out.append("")
    out.append("constexpr ControlDesc kControls[kNumControlPorts] = {")
    for p in P.CONTROL_PORTS:
        out.append('    { "%s", %sf, %sf, %sf },'
                   % (p["sym"], num(float(p["lo"])), num(float(p["hi"])),
                      num(float(p["default"]))))
    out.append("};")
    out.append("")
    out.append("} // namespace ambience")
    out.append("")

    write(PORTS_H, "\n".join(out))


# ---------------------------------------------------------------------------
# AmbienceReverb.ttl
# ---------------------------------------------------------------------------
def gen_plugin_ttl():
    out = [PROLOGUE, """@prefix doap:   <http://usefulinc.com/ns/doap#> .
@prefix foaf:   <http://xmlns.com/foaf/0.1/> .
@prefix lv2:    <http://lv2plug.in/ns/lv2core#> .
@prefix pprops: <http://lv2plug.in/ns/ext/port-props#> .
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix units:  <http://lv2plug.in/ns/extensions/units#> .

<%s>
    a lv2:Plugin , lv2:ReverbPlugin ;
    doap:name "Ambience Reverb" ;
    doap:license <https://www.gnu.org/licenses/agpl-3.0.html> ;
    doap:maintainer [
        foaf:name "OTODESK" ;
        foaf:homepage <https://github.com/OTODESK4193/Ambience1.0.1>
    ] ;
    lv2:minorVersion %d ;
    lv2:microVersion %d ;
    lv2:optionalFeature lv2:hardRTCapable ;
    rdfs:comment \"\"\"16-channel Feedback Delay Network algorithmic reverb.

FWHT feedback matrix with coprime prime-number delay allocation, seven
algorithms (Room, Hall, Plate, Spring, Goldfoil), per-channel 10-band
Valimaki-Liski cascade GEQ absorption for frequency-dependent RT60,
ISM early reflections, ADAA saturation, ducking and a brick-wall limiter.\"\"\" ;
""" % (URI, VERSION[0], VERSION[1])]

    port_blocks = []

    for i, (sym, name, direction) in enumerate(P.AUDIO_PORTS):
        cls = "lv2:InputPort" if direction == "input" else "lv2:OutputPort"
        port_blocks.append("""    [
        a %s , lv2:AudioPort ;
        lv2:index %d ;
        lv2:symbol "%s" ;
        lv2:name "%s"
    ]""" % (cls, i, sym, name))

    for i, p in enumerate(P.CONTROL_PORTS):
        idx = P.FIRST_CONTROL_INDEX + i
        lines = ["        a lv2:InputPort , lv2:ControlPort ;",
                 "        lv2:index %d ;" % idx,
                 '        lv2:symbol "%s" ;' % p["sym"],
                 '        lv2:name "%s" ;' % p["name"]]

        props = []
        if p["kind"] == "enum":
            props += ["lv2:integer", "lv2:enumeration"]
        elif p["kind"] == "bool":
            props += ["lv2:toggled"]
        elif p["skew"] < 1.0:
            # LV2's only nonlinear taper. Not identical to a JUCE skew but the
            # same intent: put the useful range under the first half of the
            # knob. predelay keeps skew 1.0 precisely because its 0.0 minimum
            # makes a logarithmic taper undefined.
            props += ["pprops:logarithmic"]

        for prop in props:
            lines.append("        lv2:portProperty %s ;" % prop)

        is_int = p["kind"] in ("enum", "bool")
        conv = int if is_int else float
        lines.append("        lv2:default %s ;" % num(conv(p["default"])))
        lines.append("        lv2:minimum %s ;" % num(conv(p["lo"])))
        lines.append("        lv2:maximum %s" % num(conv(p["hi"])))

        if p["points"]:
            lines[-1] += " ;"
            # One predicate, a comma-separated object list. Repeating
            # `lv2:scalePoint` after each comma is not Turtle.
            pts = ['[ rdfs:label "%s" ; rdf:value %d ]' % (label, v)
                   for v, label in enumerate(p["points"])]
            lines.append("        lv2:scalePoint "
                         + (" ,\n" + " " * 23).join(pts))

        if p["unit"]:
            lines[-1] += " ;"
            lines.append("        units:unit %s" % UNIT_TTL[p["unit"]])

        port_blocks.append("    [\n" + "\n".join(lines) + "\n    ]")

    out.append("    lv2:port\n" + " ,\n".join(port_blocks) + " .\n")
    write(os.path.join(BUNDLE, "AmbienceReverb.ttl"), "\n".join(out))


# ---------------------------------------------------------------------------
# modgui.ttl
# ---------------------------------------------------------------------------
def gen_modgui_ttl():
    entries = []
    for i, p in enumerate(P.CONTROL_PORTS):
        entries.append("""        [
            lv2:index %d ;
            lv2:symbol "%s" ;
            lv2:name "%s"
        ]""" % (P.FIRST_CONTROL_INDEX + i, p["sym"], p["name"]))

    body = """%s@prefix lv2:    <http://lv2plug.in/ns/lv2core#> .
@prefix modgui: <http://moddevices.com/ns/modgui#> .

<%s>
    modgui:gui [
        modgui:resourcesDirectory <modgui> ;
        modgui:iconTemplate <modgui/icon-ambience.html> ;
        modgui:stylesheet <modgui/stylesheet-ambience.css> ;
        modgui:javascript <modgui/javascript.js> ;
        modgui:screenshot <modgui/screenshot-ambience.png> ;
        modgui:thumbnail <modgui/thumbnail-ambience.png> ;
        modgui:brand "OTODESK" ;
        modgui:label "Ambience" ;
        modgui:port
%s ;
    ] .
""" % (PROLOGUE, URI, " ,\n".join(entries))

    write(os.path.join(BUNDLE, "modgui.ttl"), body)


# ---------------------------------------------------------------------------
# modgui/javascript.js
# ---------------------------------------------------------------------------
def gen_javascript():
    """Substitute the algorithm re-seed table into javascript.js.in.

    Same seven values loadPresetDefaults() writes, plus the neutral resets it
    forces, so the modgui's behaviour on an algorithm change cannot drift from
    what the VST3 does. See javascript.js.in for why this is GUI-side at all.
    """
    src = os.path.join(BUNDLE, "modgui", "javascript.js.in")
    template = open(src, encoding="utf-8").read()

    rows = []
    for i, (_label, values) in enumerate(algorithm_default_presets()):
        # Only the ports loadPresetDefaults() actually touches.
        touched = ["roomsize", "decaytime", "hfdamping", "lfabsorption",
                   "diffusion", "modamount", "modrate", "erlevel", "saturation",
                   "tiltlow", "tiltmid", "tilthigh"] \
                  + ["rtband%d" % b for b in range(10)]
        pairs = ", ".join("%s: %s" % (s, num(values[s])) for s in touched)
        rows.append("        /* %-8s */ { %s }" % (P.ALGORITHMS[i], pairs))

    table = ("    /* From PRESET_DEFAULTS in Source/AlgorithmPresets.h, via\n"
             "       loadPresetDefaults(). hfDamp/lfAbsorb from that table are\n"
             "       deliberately ignored and forced to 0, exactly as the VST3\n"
             "       does: picking an algorithm should reproduce that\n"
             "       algorithm's own RT60 curve with no correction on top. */\n"
             "    var ALGORITHM_DEFAULTS = [\n"
             + ",\n".join(rows) + "\n    ];")

    marker = "    /* [ALGORITHM_DEFAULTS] */"
    if marker not in template:
        raise ValueError("javascript.js.in lost its [ALGORITHM_DEFAULTS] marker")

    write(os.path.join(BUNDLE, "modgui", "javascript.js"),
          template.replace(marker, table))


# ---------------------------------------------------------------------------
# presets
# ---------------------------------------------------------------------------
def read_ambpreset(path):
    """Pull the parameter map out of a .ambpreset.

    The file is juce::copyXmlToBinary output: a small binary header ('VC2!'
    magic plus a size field) followed by the literal XML. Rather than decode
    the header we just seek to the '<?xml' marker, which is stable across
    every file here.

    Three quirks, present in all 21:
      * 'crossfeed' and 'oversampling' are parameters that no longer exist in
        the layout - dropped.
      * hicut is written as <PARAM id="hicut"/> with NO value attribute, so it
        falls back to its default. Preserved as a default rather than guessed.
      * a 'currentPresetName' property may be present - not a parameter.
    """
    raw = open(path, "rb").read()
    start = raw.find(b"<?xml")
    if start < 0:
        raise ValueError("%s: no XML payload" % path)
    text = raw[start:].decode("utf-8", "replace")

    values = {}
    for m in re.finditer(r'<PARAM\s+id="([^"]+)"(?:\s+value="([^"]*)")?\s*/>', text):
        pid, val = m.group(1), m.group(2)
        if pid not in P.BY_SYM:
            continue                      # crossfeed, oversampling
        if val is None or val == "":
            continue                      # hicut - leave at default
        values[pid] = float(val)
    return values


def full_port_map(values):
    """Fill every port. A preset that omits a port leaves whatever the
    previous preset set, so partial presets make the plugin's sound depend on
    load order. All 36 always."""
    out = {}
    for p in P.CONTROL_PORTS:
        v = values.get(p["sym"], p["default"])
        v = max(float(p["lo"]), min(float(p["hi"]), float(v)))
        out[p["sym"]] = int(round(v)) if p["kind"] in ("enum", "bool") else v
    return out


def parse_preset_defaults():
    """PRESET_DEFAULTS[7] out of Source/AlgorithmPresets.h.

    Parsed rather than retyped so the seven '<ALGO> Default' presets cannot
    drift from the values the DSP would have loaded.
    """
    src = open(os.path.join(REPO, "Source", "AlgorithmPresets.h"),
               encoding="utf-8").read()

    m = re.search(r"PRESET_DEFAULTS\s*=\s*\{\s*\{(.*?)\}\s*\}\s*;", src, re.S)
    if not m:
        raise ValueError("PRESET_DEFAULTS not found in AlgorithmPresets.h")

    body = re.sub(r"//[^\n]*", "", m.group(1))
    rows = re.findall(r"\{([^{}]*)\}", body)
    if len(rows) != 7:
        raise ValueError("expected 7 PRESET_DEFAULTS rows, got %d" % len(rows))

    keys = ["roomSize", "decayTime", "hfDamp", "lfAbsorb", "diffusion",
            "modAmount", "modRate", "erLevel", "saturation"]
    out = []
    for row in rows:
        nums = [float(x) for x in re.findall(r"-?\d+\.?\d*(?=f)", row)]
        if len(nums) != 9:
            raise ValueError("expected 9 fields, got %d in %r" % (len(nums), row))
        out.append(dict(zip(keys, nums)))
    return out


def algorithm_default_presets():
    """The seven per-algorithm starting points.

    Mirrors FDNReverbAudioProcessor::loadPresetDefaults(). Note it deliberately
    IGNORES def.hfDamp / def.lfAbsorb and forces both to 0, along with all ten
    rtband trims and the three tilts - the comment there is explicit that
    selecting an algorithm should reproduce that algorithm's own RT60 curve
    with no correction layered on top.
    """
    defaults = parse_preset_defaults()
    presets = []

    for i, d in enumerate(defaults):
        v = {p["sym"]: p["default"] for p in P.CONTROL_PORTS}
        v["algorithm"] = i
        v["roomsize"] = d["roomSize"]
        v["decaytime"] = d["decayTime"]
        v["diffusion"] = d["diffusion"]
        v["modamount"] = d["modAmount"]
        v["modrate"] = d["modRate"]
        v["erlevel"] = d["erLevel"]
        v["saturation"] = d["saturation"]
        v["hfdamping"] = 0.0
        v["lfabsorption"] = 0.0
        for b in range(10):
            v["rtband%d" % b] = 1.0
        v["tiltlow"] = v["tiltmid"] = v["tilthigh"] = 1.0

        presets.append(("%s Default" % P.ALGORITHMS[i], v))

    return presets


def slug(label):
    return re.sub(r"[^A-Za-z0-9]+", "-", label).strip("-")


def collect_presets():
    """21 factory + 7 algorithm defaults, grouped by algorithm."""
    factory = []
    pdir = os.path.join(REPO, "Presets")
    for fn in sorted(os.listdir(pdir)):
        if not fn.endswith(".ambpreset"):
            continue
        label = fn[: -len(".ambpreset")]
        factory.append((label, full_port_map(read_ambpreset(os.path.join(pdir, fn)))))

    if len(factory) != 21:
        print("  warning: expected 21 factory presets, found %d" % len(factory))

    algo = [(label, full_port_map(v)) for label, v in algorithm_default_presets()]

    both = factory + algo
    both.sort(key=lambda kv: (kv[1]["algorithm"],
                              not kv[0].endswith("Default"),
                              kv[0]))
    return both


def preset_stanza(uri, label, values):
    ports = ",\n".join(
        '\t\t[ lv2:symbol "%s" ; pset:value %s ]' % (p["sym"], num(values[p["sym"]]))
        for p in P.CONTROL_PORTS)
    return """%s
\ta pset:Preset ;
\tlv2:appliesTo <%s> ;
\trdfs:label %s ;
\tlv2:port
%s .
""" % (uri, URI, ttl_string(label), ports)


def gen_presets(presets):
    header = """%s@prefix lv2:  <http://lv2plug.in/ns/lv2core#> .
@prefix pset: <http://lv2plug.in/ns/ext/presets#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

""" % PROLOGUE

    body = [header]
    for label, values in presets:
        body.append(preset_stanza("<%s%s>" % (PRESET_NS, slug(label)), label, values))
    write(os.path.join(BUNDLE, "presets.ttl"), "\n".join(body))

    # The subject must be the SAME relative URI the manifest declares, i.e.
    # <default-preset>, not <>. Both resolve against their own file's base, so
    # <> here would name default-preset.ttl while the manifest names
    # <bundle>/default-preset - two different subjects, and lilv would find a
    # preset with no port values. MOD's own bundles use <default-preset> in
    # both files for exactly this reason (mod-mda-Leslie.lv2).
    defaults = full_port_map({})
    write(os.path.join(BUNDLE, "default-preset.ttl"),
          header + preset_stanza("<default-preset>", "Default", defaults))


# ---------------------------------------------------------------------------
# manifest.ttl
# ---------------------------------------------------------------------------
def gen_manifest(presets):
    """MOD's convention: declare every preset inline in the manifest and point
    at the data file with rdfs:seeAlso, so mod-ui can list them without
    parsing presets.ttl. See mod-mda-Leslie.lv2/manifest.ttl."""
    out = ["""%s@prefix lv2:  <http://lv2plug.in/ns/lv2core#> .
@prefix pset: <http://lv2plug.in/ns/ext/presets#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<%s>
    a lv2:Plugin ;
    lv2:binary <AmbienceReverb.so> ;
    rdfs:seeAlso <AmbienceReverb.ttl> , <modgui.ttl> .

<default-preset>
    a pset:Preset ;
    lv2:appliesTo <%s> ;
    rdfs:label "Default" ;
    rdfs:seeAlso <default-preset.ttl> .
""" % (PROLOGUE, URI, URI)]

    for label, _ in presets:
        out.append("""<%s%s>
    a pset:Preset ;
    lv2:appliesTo <%s> ;
    rdfs:label %s ;
    rdfs:seeAlso <presets.ttl> .
""" % (PRESET_NS, slug(label), URI, ttl_string(label)))

    write(os.path.join(BUNDLE, "manifest.ttl"), "\n".join(out))


# ---------------------------------------------------------------------------
def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("  %s" % os.path.relpath(path, REPO))


def main():
    print("Generating:")
    gen_ports_h()
    gen_plugin_ttl()
    gen_modgui_ttl()
    gen_javascript()
    presets = collect_presets()
    gen_presets(presets)
    gen_manifest(presets)
    print("\n%d control ports, %d presets (+ Default)"
          % (len(P.CONTROL_PORTS), len(presets)))


if __name__ == "__main__":
    main()
