#pragma once

#define AMBIENCE_MAJOR_VERSION 2
#define AMBIENCE_MINOR_VERSION 0
#define AMBIENCE_PATCH_VERSION 2
#define AMBIENCE_VERSION_STRING "2.0.2"
#define AMBIENCE_BUILD_NUMBER   "B002"
#define AMBIENCE_FULL_TITLE     "AMBIENCE 2.0.2 B002"
